"""Curated starter recipe library (Spanish, Ecuador-friendly), seeded on first use."""

FLICKR = "CC BY 2.0"

# (slug, name, category, description, servings, minutes, kcal, protein, carbs,
#  fat, fiber, diet, allergens, tags, ingredients, steps, (creator, license, source))
_R = [
    (
        "avena-frutos-rojos",
        "Avena con frutos rojos y chía",
        "breakfast",
        "Desayuno con fibra que ayuda a que la glucosa suba despacio.",
        1,
        10,
        320,
        11,
        48,
        9,
        9,
        "vegetarian",
        ["gluten", "lactose"],
        ["high_fiber", "low_gi", "no_added_sugar"],
        [
            "1/2 taza (40 g) de avena en hojuelas",
            "1 taza de leche descremada o bebida vegetal sin azúcar",
            "1/2 taza de frutos rojos (fresas, moras, arándanos)",
            "1 cucharada de semillas de chía",
            "Canela al gusto",
        ],
        [
            "Cocina la avena con la leche 5 minutos a fuego bajo, removiendo.",
            "Retira del fuego y añade la chía y la canela.",
            "Sirve con los frutos rojos por encima, sin añadir azúcar.",
        ],
        (
            "Denna Jones",
            FLICKR,
            "https://www.flickr.com/photos/95267793@N00/2732313297",
        ),
    ),
    (
        "huevos-espinaca",
        "Huevos revueltos con espinaca y pan integral",
        "breakfast",
        "Proteína desde la mañana para tener más saciedad.",
        1,
        10,
        330,
        20,
        24,
        16,
        5,
        "vegetarian",
        ["egg", "gluten"],
        ["high_protein", "low_gi", "quick"],
        [
            "2 huevos",
            "1 taza de espinaca fresca",
            "1/2 tomate picado",
            "1 rebanada de pan integral",
            "1 cucharadita de aceite de oliva",
            "Pimienta y poca sal",
        ],
        [
            "Saltea la espinaca y el tomate en el aceite 2 minutos.",
            "Añade los huevos batidos y remueve hasta que cuajen.",
            "Sirve con el pan integral tostado.",
        ],
        ("ultrakml", FLICKR, "https://www.flickr.com/photos/34948727@N00/8121597563"),
    ),
    (
        "yogur-nueces",
        "Yogur natural con nueces, manzana y canela",
        "breakfast",
        "Rápido, con proteína y grasas saludables, sin azúcar añadido.",
        1,
        5,
        280,
        15,
        26,
        13,
        4,
        "vegetarian",
        ["lactose", "nuts"],
        ["high_protein", "no_added_sugar", "quick"],
        [
            "1 taza de yogur natural sin azúcar (o griego)",
            "1/2 manzana picada con cáscara",
            "1 cucharada de nueces picadas",
            "1 cucharadita de linaza",
            "Canela al gusto",
        ],
        [
            "Pon el yogur en un bol.",
            "Añade la manzana, las nueces, la linaza y la canela.",
            "Cómelo enseguida para que la manzana no se oscurezca.",
        ],
        ("grongar", FLICKR, "https://www.flickr.com/photos/70757891@N00/5537372504"),
    ),
    (
        "tostada-aguacate",
        "Tostada integral con aguacate y huevo",
        "breakfast",
        "Grasas saludables y fibra en un desayuno muy completo.",
        1,
        12,
        350,
        15,
        26,
        21,
        8,
        "vegetarian",
        ["gluten", "egg"],
        ["high_fiber", "low_gi"],
        [
            "1 rebanada de pan integral",
            "1/2 aguacate",
            "1 huevo",
            "Jugo de limón",
            "Tomate cherry y hojas verdes",
            "Pimienta y una pizca de sal",
        ],
        [
            "Tuesta el pan.",
            "Aplasta el aguacate con limón y pimienta y úntalo.",
            "Cuece el huevo en agua apenas hirviendo 3–4 minutos y ponlo encima.",
            "Acompaña con tomate y hojas verdes.",
        ],
        (
            "Stacy Spensley",
            FLICKR,
            "https://www.flickr.com/photos/21001756@N06/4532239153",
        ),
    ),
    (
        "tofu-revuelto",
        "Tofu revuelto con cúrcuma y verduras",
        "breakfast",
        "Alternativa vegetal a los huevos, alta en proteína.",
        2,
        15,
        260,
        18,
        12,
        15,
        4,
        "vegan",
        ["soy"],
        ["high_protein", "low_gi"],
        [
            "250 g de tofu firme",
            "1/2 pimiento picado",
            "1/2 cebolla picada",
            "1 taza de espinaca",
            "1/2 cucharadita de cúrcuma",
            "1 cucharadita de aceite de oliva",
            "1/4 de aguacate para servir",
        ],
        [
            "Sofríe la cebolla y el pimiento en el aceite.",
            "Desmenuza el tofu con un tenedor y añádelo con la cúrcuma.",
            "Agrega la espinaca y cocina 3 minutos más.",
            "Sirve con el aguacate.",
        ],
        (
            "watashiwani",
            FLICKR,
            "https://www.flickr.com/photos/11316976@N00/4186548010",
        ),
    ),
    (
        "ensalada-quinua",
        "Ensalada de quinua, garbanzo y verduras",
        "lunch",
        "Plato vegetal con proteína y mucha fibra.",
        2,
        25,
        420,
        16,
        55,
        14,
        11,
        "vegan",
        [],
        ["high_fiber", "low_gi", "low_sodium"],
        [
            "1/2 taza de quinua cruda, bien lavada",
            "1 taza de garbanzos cocidos",
            "1 pepino picado",
            "1 tomate picado",
            "1/2 pimiento rojo",
            "Cilantro y cebolla colorada",
            "1 cucharada de aceite de oliva y el jugo de 1 limón",
        ],
        [
            "Cocina la quinua en 1 taza de agua 15 minutos y deja enfriar.",
            "Pica las verduras.",
            "Mezcla todo con los garbanzos y aliña con aceite, limón y poca sal.",
        ],
        ("rusvaplauke", FLICKR, "https://www.flickr.com/photos/7440954@N05/901705743"),
    ),
    (
        "pollo-verduras",
        "Pechuga de pollo a la plancha con verduras salteadas",
        "lunch",
        "El método del plato en una receta: verduras, proteína y un poco de integral.",
        1,
        25,
        400,
        38,
        30,
        13,
        7,
        "omnivore",
        [],
        ["high_protein", "low_gi", "low_fat"],
        [
            "120 g de pechuga de pollo sin piel",
            "1 taza de brócoli",
            "1 zanahoria en tiras",
            "1/2 zucchini",
            "1/2 taza de arroz integral cocido",
            "1 cucharadita de aceite de oliva",
            "Ajo, comino y limón",
        ],
        [
            "Marina el pollo con ajo, comino y limón 10 minutos.",
            "Cocínalo a la plancha 5–6 minutos por lado.",
            "Saltea las verduras en el aceite 4 minutos, que queden crujientes.",
            "Sirve: mitad del plato verduras, un cuarto pollo y un cuarto arroz integral.",
        ],
        ("jshontz", FLICKR, "https://www.flickr.com/photos/29332685@N07/7494195880"),
    ),
    (
        "menestra-lentejas",
        "Menestra de lentejas con arroz integral y ensalada",
        "lunch",
        "Clásico ecuatoriano en versión integral, con mucha fibra.",
        4,
        40,
        430,
        20,
        70,
        7,
        16,
        "vegan",
        [],
        ["high_fiber", "low_gi", "low_fat"],
        [
            "1 taza de lentejas crudas",
            "1 cebolla, 1 pimiento y 2 dientes de ajo",
            "1 tomate rallado",
            "1 cucharadita de comino y achiote",
            "1 taza de arroz integral crudo",
            "Ensalada de tomate, cebolla y cilantro con limón",
        ],
        [
            "Haz un refrito con la cebolla, el pimiento, el ajo, el tomate, el comino y el achiote.",
            "Añade las lentejas lavadas y 4 tazas de agua; cocina 30 minutos.",
            "Cocina el arroz integral aparte.",
            "Sirve media taza de arroz por persona y abundante ensalada.",
        ],
        ("bobjudge", FLICKR, "https://www.flickr.com/photos/8286199@N08/4068315591"),
    ),
    (
        "ceviche",
        "Ceviche de pescado con mote",
        "lunch",
        "Proteína magra y fresca; acompáñalo con mote o camote en vez de chifles.",
        2,
        30,
        280,
        30,
        18,
        8,
        3,
        "pescatarian",
        ["fish"],
        ["high_protein", "low_fat", "low_gi"],
        [
            "300 g de pescado blanco fresco en cubos",
            "Jugo de 8 limones",
            "1 cebolla colorada en pluma",
            "1 tomate picado",
            "Cilantro picado",
            "1 cucharada de aceite de oliva",
            "1/2 taza de mote o camote cocido",
        ],
        [
            "Cubre el pescado con el jugo de limón y deja reposar 15–20 minutos en la refrigeradora.",
            "Añade la cebolla, el tomate, el cilantro y el aceite.",
            "Ajusta con poca sal y sirve frío.",
            "Acompaña con mote o camote en lugar de frituras.",
        ],
        ("Pixel Drip", FLICKR, "https://www.flickr.com/photos/94336982@N00/41489558"),
    ),
    (
        "bowl-salmon",
        "Bowl de salmón, arroz integral y aguacate",
        "lunch",
        "Rico en omega-3, que ayuda a bajar los triglicéridos.",
        1,
        20,
        520,
        32,
        45,
        23,
        8,
        "pescatarian",
        ["fish", "soy", "sesame"],
        ["omega3", "high_protein"],
        [
            "120 g de salmón fresco o en lata al natural",
            "1/2 taza de arroz integral cocido",
            "1/4 de aguacate",
            "1/2 pepino",
            "1 zanahoria rallada",
            "Hojas verdes",
            "1 cucharadita de sésamo y salsa de soya baja en sodio",
        ],
        [
            "Cocina el salmón a la plancha 3–4 minutos por lado (o usa salmón en lata escurrido).",
            "Pon el arroz en un bol con las verduras y el aguacate.",
            "Añade el salmón en trozos, el sésamo y unas gotas de salsa de soya.",
        ],
        (
            "silvar.net",
            FLICKR,
            "https://www.flickr.com/photos/34811759@N08/50672248857",
        ),
    ),
    (
        "ceviche-chochos",
        "Ceviche de chochos",
        "lunch",
        "Leguminosa andina con mucha proteína y fibra.",
        2,
        15,
        300,
        18,
        22,
        14,
        8,
        "vegan",
        [],
        ["high_protein", "high_fiber", "low_gi"],
        [
            "2 tazas de chochos desamargados y lavados",
            "1 tomate picado",
            "1/2 cebolla colorada en pluma",
            "Jugo de 4 limones y 1 naranja",
            "Cilantro",
            "1 cucharada de aceite de oliva",
            "Tostado, solo una porción pequeña (opcional)",
        ],
        [
            "Lava bien los chochos para quitarles el exceso de sal.",
            "Mezcla la cebolla con el limón y la naranja y deja reposar 5 minutos.",
            "Añade los chochos, el tomate, el cilantro y el aceite.",
            "Sirve frío; si usas tostado, que sea poco.",
        ],
        (
            "Dtarazona (Wikimedia Commons)",
            "CC BY-SA 4.0",
            "https://commons.wikimedia.org/wiki/File:Ceviche_de_chochos_Huari_09102009.JPG",
        ),
    ),
    (
        "sopa-pollo",
        "Sopa de pollo con verduras",
        "dinner",
        "Cena ligera y saciante, sin cubitos de caldo.",
        4,
        40,
        260,
        24,
        22,
        7,
        5,
        "omnivore",
        [],
        ["high_protein", "low_fat", "low_sodium"],
        [
            "300 g de pechuga de pollo sin piel",
            "2 zanahorias",
            "1 taza de brócoli o vainitas",
            "1 zucchini",
            "1 papa pequeña",
            "Cebolla, ajo, apio y cilantro",
            "Hierbas aromáticas en vez de cubitos",
        ],
        [
            "Cocina el pollo en 2 litros de agua con la cebolla, el ajo y el apio 20 minutos.",
            "Desmenúzalo y añade las verduras picadas; cocina 15 minutos.",
            "Sazona con hierbas y poca sal, sin cubitos.",
            "Termina con cilantro picado.",
        ],
        (
            "Paul Keller",
            FLICKR,
            "https://www.flickr.com/photos/18259771@N00/5355451436",
        ),
    ),
    (
        "pescado-brocoli",
        "Pescado al horno con brócoli y salsa de tomate",
        "dinner",
        "Proteína magra con verduras, lista en media hora.",
        2,
        30,
        340,
        32,
        20,
        13,
        6,
        "pescatarian",
        ["fish"],
        ["high_protein", "low_gi"],
        [
            "2 filetes de pescado blanco (corvina o tilapia) de 150 g",
            "2 tazas de brócoli",
            "1 taza de salsa de tomate casera",
            "1 cucharada de aceite de oliva",
            "Ajo, orégano y limón",
        ],
        [
            "Precalienta el horno a 200 °C.",
            "Pon el pescado en una bandeja con el ajo, el orégano, el limón y el aceite.",
            "Cubre con la salsa de tomate y hornea 15–18 minutos.",
            "Cocina el brócoli al vapor 5 minutos y sirve todo junto.",
        ],
        ("kimberlykv", FLICKR, "https://www.flickr.com/photos/87542849@N00/5629616701"),
    ),
    (
        "tortilla-champinones",
        "Tortilla de espinaca y champiñones",
        "dinner",
        "Cena baja en carbohidratos con proteína de calidad.",
        2,
        20,
        260,
        19,
        8,
        17,
        3,
        "vegetarian",
        ["egg"],
        ["high_protein", "low_gi"],
        [
            "4 huevos",
            "1 taza de champiñones en láminas",
            "1 taza de espinaca",
            "1/2 cebolla",
            "1 cucharadita de aceite de oliva",
            "Ensalada grande para acompañar",
        ],
        [
            "Saltea la cebolla y los champiñones 4 minutos y añade la espinaca.",
            "Vierte los huevos batidos y cocina tapado a fuego bajo 6–8 minutos.",
            "Dale la vuelta con ayuda de un plato.",
            "Acompaña con una ensalada grande.",
        ],
        ("jeffreyw", FLICKR, "https://www.flickr.com/photos/7927684@N03/5182567699"),
    ),
    (
        "salteado-tofu",
        "Salteado de tofu con verduras y arroz integral",
        "dinner",
        "Plato vegetal completo con proteína y fibra.",
        2,
        25,
        430,
        22,
        45,
        18,
        7,
        "vegan",
        ["soy"],
        ["high_protein", "high_fiber"],
        [
            "250 g de tofu firme en cubos",
            "1 pimiento, 1 zanahoria y 1 taza de brócoli",
            "1/2 cebolla",
            "1 diente de ajo y jengibre rallado",
            "1 cucharada de salsa de soya baja en sodio",
            "1 cucharada de aceite",
            "1 taza de arroz integral cocido",
        ],
        [
            "Dora el tofu con la mitad del aceite y resérvalo.",
            "Saltea las verduras con el ajo y el jengibre 4–5 minutos.",
            "Añade el tofu y la salsa de soya.",
            "Sirve con media taza de arroz integral por persona.",
        ],
        (
            "KFoodaddict",
            FLICKR,
            "https://www.flickr.com/photos/61056459@N05/6229385375",
        ),
    ),
    (
        "crema-zapallo",
        "Crema de zapallo sin crema de leche",
        "dinner",
        "Cremosa y ligera; acompáñala con una proteína.",
        4,
        35,
        180,
        6,
        26,
        6,
        5,
        "vegan",
        [],
        ["low_fat", "low_sodium"],
        [
            "800 g de zapallo pelado en cubos",
            "1 cebolla y 1 diente de ajo",
            "1 zanahoria",
            "3 tazas de caldo casero de verduras",
            "1 cucharada de aceite de oliva",
            "Semillas de zapallo tostadas para servir",
        ],
        [
            "Sofríe la cebolla y el ajo en el aceite.",
            "Añade el zapallo, la zanahoria y el caldo; cocina 20 minutos.",
            "Licúa hasta que quede cremosa, sin crema de leche.",
            "Sirve con las semillas y una proteína (huevo, pollo o queso fresco).",
        ],
        (
            "Happy Tummy",
            FLICKR,
            "https://www.flickr.com/photos/29198474@N05/16424926259",
        ),
    ),
    (
        "hummus",
        "Hummus con bastones de verduras",
        "snack",
        "Refrigerio con fibra que calma el hambre entre comidas.",
        4,
        10,
        190,
        7,
        18,
        10,
        6,
        "vegan",
        ["sesame"],
        ["high_fiber", "low_gi"],
        [
            "1 1/2 tazas de garbanzos cocidos",
            "1 cucharada de tahini (pasta de sésamo)",
            "Jugo de 1 limón y 1 diente de ajo",
            "1 cucharada de aceite de oliva",
            "Zanahoria, pepino, pimiento y apio en bastones",
        ],
        [
            "Licúa los garbanzos con el tahini, el limón, el ajo, el aceite y un poco de agua.",
            "Ajusta la textura y añade poca sal.",
            "Sirve 3 cucharadas por persona con muchos bastones de verduras.",
        ],
        (
            "serenejournal",
            FLICKR,
            "https://www.flickr.com/photos/8564557@N05/2051489181",
        ),
    ),
    (
        "manzana-mani",
        "Manzana con mantequilla de maní natural",
        "snack",
        "Fruta entera con un poco de grasa saludable para más saciedad.",
        1,
        3,
        200,
        5,
        22,
        11,
        5,
        "vegan",
        ["peanut"],
        ["low_gi", "no_added_sugar", "quick"],
        [
            "1 manzana mediana",
            "1 cucharada de mantequilla de maní 100 % natural, sin azúcar",
            "Canela al gusto",
        ],
        [
            "Corta la manzana en rodajas o gajos.",
            "Acompáñala con la mantequilla de maní.",
            "Espolvorea canela.",
        ],
        ("Crystl", FLICKR, "https://www.flickr.com/photos/10953991@N00/252041504"),
    ),
    (
        "frutos-secos",
        "Puñado de frutos secos sin sal",
        "snack",
        "Grasas saludables; la clave es la porción.",
        1,
        1,
        170,
        6,
        6,
        15,
        3,
        "vegan",
        ["nuts"],
        ["low_gi", "low_sodium", "quick"],
        [
            "30 g (un puñado) de almendras, nueces o anacardos sin sal ni azúcar",
        ],
        [
            "Sirve una porción de 30 g, lo que cabe en tu palma ahuecada.",
            "Evita los tostados con sal, miel o chocolate.",
        ],
        (
            "belgianchocolate",
            FLICKR,
            "https://www.flickr.com/photos/90901507@N00/15930006",
        ),
    ),
    (
        "agua-pepino",
        "Agua de pepino, limón y hierbabuena",
        "drink",
        "Alternativa sin azúcar a gaseosas y jugos.",
        4,
        5,
        10,
        0,
        2,
        0,
        0,
        "vegan",
        [],
        ["no_added_sugar", "low_sodium", "quick"],
        [
            "1 litro de agua fría",
            "1/2 pepino en rodajas",
            "1 limón en rodajas",
            "Hojas de hierbabuena",
        ],
        [
            "Pon el pepino, el limón y la hierbabuena en una jarra.",
            "Añade el agua y deja reposar 30 minutos en la refrigeradora.",
            "Sírvela sin azúcar ni edulcorantes.",
        ],
        (
            "Elvert Barnes",
            FLICKR,
            "https://www.flickr.com/photos/95413346@N00/134176144",
        ),
    ),
    (
        "batido-verde",
        "Batido verde de espinaca, pepino y manzana",
        "drink",
        "Sin colar, para conservar toda la fibra.",
        1,
        5,
        150,
        4,
        26,
        4,
        6,
        "vegan",
        [],
        ["high_fiber", "no_added_sugar", "quick"],
        [
            "1 taza de espinaca",
            "1/2 pepino",
            "1/2 manzana verde",
            "1/4 de aguacate",
            "Jugo de 1/2 limón",
            "1 taza de agua fría y hielo",
        ],
        [
            "Licúa todo con el agua hasta que quede suave.",
            "No lo cueles: así conservas la fibra.",
            "Tómalo enseguida y sin añadir azúcar.",
        ],
        ("Wild Tofu", FLICKR, "https://www.flickr.com/photos/47218783@N05/4443377532"),
    ),
    (
        "te-hierbas",
        "Infusión de hierbas sin azúcar",
        "drink",
        "Horchata lojana, manzanilla, cedrón o toronjil, sin calorías.",
        1,
        5,
        5,
        0,
        1,
        0,
        0,
        "vegan",
        [],
        ["no_added_sugar", "low_sodium", "quick"],
        [
            "1 taza de agua",
            "1 cucharada de hierbas secas o un puñado de frescas",
            "Una rodaja de limón (opcional)",
        ],
        [
            "Hierve el agua y viértela sobre las hierbas.",
            "Tapa, deja reposar 5 minutos y cuela.",
            "Tómala sin azúcar; si te cuesta, reduce el azúcar poco a poco.",
        ],
        ("Forban300", FLICKR, "https://www.flickr.com/photos/64277901@N08/5872068364"),
    ),
    (
        "batido-frutos-rojos",
        "Batido de frutos rojos con yogur",
        "drink",
        "Con proteína del yogur; la fruta ya aporta el dulzor.",
        1,
        5,
        210,
        13,
        28,
        5,
        6,
        "vegetarian",
        ["lactose", "gluten"],
        ["high_protein", "no_added_sugar", "quick"],
        [
            "3/4 de taza de yogur natural sin azúcar",
            "1 taza de frutos rojos frescos o congelados",
            "1 cucharada de avena",
            "1/2 taza de agua o leche descremada",
            "Hielo",
        ],
        [
            "Licúa todo hasta que quede cremoso.",
            "Prueba antes de endulzar: la fruta ya aporta dulzor.",
            "Sirve frío.",
        ],
        ("VegaTeam", FLICKR, "https://www.flickr.com/photos/59256189@N04/5867754540"),
    ),
]

DIET_LEVELS = {
    "omnivore": ["omnivore", "other"],
    "pescatarian": ["omnivore", "other", "pescatarian"],
    "vegetarian": ["omnivore", "other", "pescatarian", "vegetarian"],
    "vegan": ["omnivore", "other", "pescatarian", "vegetarian", "vegan"],
}


def library_recipes():
    out = []
    for (
        slug,
        name,
        category,
        description,
        servings,
        minutes,
        kcal,
        protein,
        carbs,
        fat,
        fiber,
        diet,
        allergens,
        tags,
        ingredients,
        steps,
        credit,
    ) in _R:
        creator, license_name, source = credit
        out.append(
            {
                "slug": slug,
                "name": name,
                "category": category,
                "description": description,
                "servings": servings,
                "prep_minutes": minutes,
                "kcal": kcal,
                "protein_g": protein,
                "carbs_g": carbs,
                "fat_g": fat,
                "fiber_g": fiber,
                "diets": DIET_LEVELS[diet],
                "allergens": allergens,
                "tags": tags,
                "ingredients": ingredients,
                "steps": steps,
                "image_url": f"/recipes/{slug}.jpg",
                "image_credit": f"{creator} · {license_name}",
                "image_source_url": source,
                "language": "es",
                "is_library": True,
                "is_active": True,
            }
        )
    return out
